version: '3.6'

services:

  telegram:
    build: ./telegram
    container_name: telegram
    environment:
      - REACT_APP_TELEGRAM_API_ID_FILE=/run/secrets/TELEGRAM_API_ID
      - REACT_APP_TELEGRAM_API_HASH_FILE=/run/secrets/TELEGRAM_API_HASH
    secrets:
      - TELEGRAM_API_ID
      - TELEGRAM_API_HASH
    restart: unless-stopped

secrets:
  TELEGRAM_API_ID:
    file: ./secrets/telegram_api_id
  TELEGRAM_API_HASH:
    file: ./secrets/telegram_api_hash
